version: 2.1

jobs:
  testcache:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
          version: 19.03.12
      - run: docker build .

workflows:
  wf:
    jobs:
      - testcache
